package com.paymentplatform.embeddedpayments.auth.application;

import com.paymentplatform.embeddedpayments.auth.domain.entity.AuthRole;
import com.paymentplatform.embeddedpayments.auth.domain.entity.UserAccount;
import com.paymentplatform.embeddedpayments.auth.infrastructure.repository.AuthRoleJpaRepository;
import com.paymentplatform.embeddedpayments.auth.infrastructure.repository.UserAccountJpaRepository;
import com.paymentplatform.embeddedpayments.merchant.application.RegisterMerchantUseCase;
import com.paymentplatform.embeddedpayments.shared.exception.ConflictException;
import com.paymentplatform.embeddedpayments.shared.exception.DomainException;
import java.time.Instant;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

@Service
public class RegisterUserUseCase {

    private static final String ADMIN = "ADMIN";
    private static final String USER = "USER";

    private final UserAccountJpaRepository userAccountRepository;
    private final AuthRoleJpaRepository authRoleRepository;
    private final PasswordEncoder passwordEncoder;
    private final RegisterMerchantUseCase registerMerchantUseCase;

    public RegisterUserUseCase(UserAccountJpaRepository userAccountRepository,
                               AuthRoleJpaRepository authRoleRepository,
                               PasswordEncoder passwordEncoder,
                               RegisterMerchantUseCase registerMerchantUseCase) {
        this.userAccountRepository = userAccountRepository;
        this.authRoleRepository = authRoleRepository;
        this.passwordEncoder = passwordEncoder;
        this.registerMerchantUseCase = registerMerchantUseCase;
    }

    public RegisteredUser execute(String email, String password, String role, String merchantName) {
        String normalizedEmail = email.trim().toLowerCase();
        String normalizedRole = normalizeRole(role);
        validatePassword(password);

        userAccountRepository.findByEmail(normalizedEmail).ifPresent(existing -> {
            throw new ConflictException(
                    "USER_ALREADY_EXISTS",
                    "User already exists for email",
                    List.of("email: " + normalizedEmail)
            );
        });

        String roleName = toSpringRole(normalizedRole);
        AuthRole authRole = authRoleRepository.findByName(roleName)
                .orElseGet(() -> authRoleRepository.save(new AuthRole(roleName, "Generated by application")));

        UUID merchantId = null;
        String apiKey = null;
        if (ADMIN.equals(normalizedRole)) {
            if (merchantName == null || merchantName.isBlank()) {
                throw new DomainException(
                        HttpStatus.BAD_REQUEST,
                        "MERCHANT_NAME_REQUIRED",
                        "merchantName is required for ADMIN users",
                        List.of("role: ADMIN")
                );
            }

            RegisterMerchantUseCase.RegisteredMerchant registeredMerchant =
                    registerMerchantUseCase.execute(merchantName, normalizedEmail);
            merchantId = registeredMerchant.merchant().getId();
            apiKey = registeredMerchant.apiKey();
        }

        UserAccount userAccount = new UserAccount(
                UUID.randomUUID(),
                normalizedEmail,
                passwordEncoder.encode(password),
                "ACTIVE",
                Instant.now(),
                Set.of(authRole)
        );

        UserAccount savedUser = userAccountRepository.save(userAccount);
        return new RegisteredUser(
                savedUser.getId(),
                savedUser.getEmail(),
                savedUser.getStatus(),
                roleName,
                merchantId,
                apiKey
        );
    }

    private String normalizeRole(String role) {
        if (role == null || role.isBlank()) {
            return USER;
        }

        String normalized = role.trim().toUpperCase();
        if (!ADMIN.equals(normalized) && !USER.equals(normalized)) {
            throw new DomainException(
                    HttpStatus.BAD_REQUEST,
                    "INVALID_ROLE",
                    "Role must be ADMIN or USER",
                    List.of("role: " + role)
            );
        }
        return normalized;
    }

    private String toSpringRole(String role) {
        if (ADMIN.equals(role)) {
            return "ROLE_ADMIN";
        }
        return "ROLE_USER";
    }

    private void validatePassword(String password) {
        if (password == null || password.length() < 8) {
            throw new DomainException(
                    HttpStatus.BAD_REQUEST,
                    "WEAK_PASSWORD",
                    "Password must have at least 8 characters",
                    List.of()
            );
        }
    }

    public record RegisteredUser(
            UUID id,
            String email,
            String status,
            String role,
            UUID merchantId,
            String apiKey) {
    }
}
